SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Shippers';
ALTER TRIGGER trg_ShipperInsert
ON Shippers
AFTER INSERT
AS
BEGIN
    SELECT * FROM INSERTED;
END;
INSERT INTO Shippers VALUES ('Test Shipper', '111-222');
